{
 "title": "Humain data",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Detection accuracy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  accuracy\nFROM events\nWHERE\n  $__timeFilter(time) AND\n  entity = 'homme'\nORDER BY time"
    }
   ]
  },
  {
   "title": "Accuracy",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  accuracy\nFROM events\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Number of humain per day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  count(id) AS \"id\"\nFROM events\nWHERE\n  $__timeFilter(time) AND\n  entity = 'homme'\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  }
 ]
}