{
 "title": "New dashboard Copy",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Global accuracy",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  accuracy AS \"Chamois\"\nFROM events\nWHERE\n  $__timeFilter(time) AND\n  entity = 'chamois'\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  accuracy AS \"Loup\"\nFROM events\nWHERE\n  $__timeFilter(time) AND\n  entity = 'loup'\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  accuracy AS \"Homme\"\nFROM events\nWHERE\n  $__timeFilter(time) AND\n  entity = 'homme'\nORDER BY time"
    }
   ]
  },
  {
   "title": "Heatmap days",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  count(id) AS \"Nb Chamois\"\nFROM events\nWHERE\n  $__timeFilter(time) AND\n  entity = 'chamois'\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  count(id) AS \"Nb Homme\"\nFROM events\nWHERE\n  $__timeFilter(time) AND\n  entity = 'homme'\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  count(id) AS \"Nb loup\"\nFROM events\nWHERE\n  $__timeFilter(time) AND\n  entity = 'loup'\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "Accuracy per day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  accuracy\nFROM events\nWHERE\n  $__timeFilter(time) AND\n  entity = 'chamois'\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  accuracy\nFROM events\nWHERE\n  $__timeFilter(time) AND\n  entity = 'homme'\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  accuracy\nFROM events\nWHERE\n  $__timeFilter(time) AND\n  entity = 'loup'\nORDER BY time"
    }
   ]
  },
  {
   "title": "Count Homme",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  sum(id) AS \"id\"\nFROM events\nWHERE\n  $__timeFilter(time) AND\n  entity = 'homme'\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  }
 ]
}