{
 "title": "Main Dashboard",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Global accuracy",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  accuracy AS \"Chamois\"\nFROM events\nWHERE\n  $__timeFilter(time) AND\n  entity = 'chamois'\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  accuracy AS \"Loup\"\nFROM events\nWHERE\n  $__timeFilter(time) AND\n  entity = 'loup'\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  accuracy AS \"Homme\"\nFROM events\nWHERE\n  $__timeFilter(time) AND\n  entity = 'homme'\nORDER BY time"
    }
   ]
  },
  {
   "title": "Accuracy per day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  accuracy\nFROM events\nWHERE\n  $__timeFilter(time) AND\n  entity = 'chamois'\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  accuracy\nFROM events\nWHERE\n  $__timeFilter(time) AND\n  entity = 'homme'\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  accuracy\nFROM events\nWHERE\n  $__timeFilter(time) AND\n  entity = 'loup'\nORDER BY time"
    }
   ]
  },
  {
   "title": "Test copy",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(`time`) as time_sec,\n  `devEUI` as name,\n  `batteryLevel` as metric,\n  `latitude` as latitude,\n  `longitude` as longitude\nFROM devices\nWHERE $__timeFilter(`time`)\nORDER BY `time` ASC"
    }
   ]
  },
  {
   "title": "Heatmap days",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  count(id) AS \"Nb Chamois\"\nFROM events\nWHERE\n  $__timeFilter(time) AND\n  entity = 'chamois'\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  count(id) AS \"Nb Homme\"\nFROM events\nWHERE\n  $__timeFilter(time) AND\n  entity = 'homme'\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  count(id) AS \"Nb loup\"\nFROM events\nWHERE\n  $__timeFilter(time) AND\n  entity = 'loup'\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "Number of chamois per day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  count(id) AS \"id\"\nFROM events\nWHERE\n  $__timeFilter(time) AND\n  entity = 'chamois'\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "Number of humain per day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  count(id) AS \"id\"\nFROM events\nWHERE\n  $__timeFilter(time) AND\n  entity = 'homme'\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "Number of wolf per day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  count(id) AS \"id\"\nFROM events\nWHERE\n  $__timeFilter(time) AND\n  entity = 'loup'\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "Number of rabbits per day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  count(id) AS \"id\"\nFROM events\nWHERE\n  $__timeFilter(time) AND\n  entity = 'lièvre'\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  }
 ]
}